version 0.0
#Might need to be a different OS
os: linux

files: 
  - source: /
#  may need to not be server
    desitnation: /home/ec2-user/server
    
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    
hooks:
  BeforeInstall:
    - location: server_clear.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: server_clear.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: server_start.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: server_stop.sh
      timeout: 300
      runas: ec2-user