version: 0.2

phases:
  install:
    commands:
      - echo "          ((((((((((     updating existing packages START     ))))))))))        "
      - sudo yum update -y
      - echo "          ((((((((((     updating existing packages END     ))))))))))          "
      - echo "          ((((((((((     install a couple tools that may be helpful for later START     ))))))))))          "
      - sudo yum install wget -y
      - sudo yum install unzip -y
      - sudo yum install lsof -y
      - echo "          ((((((((((     install a couple tools that may be helpful for later END     ))))))))))          "
    finally:
      - echo This always runs even if the update or install command fails 
  pre_build:
    commands:
      - echo Entered the pre_build phase...
    finally:
      - echo This always runs even if the login command fails 
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`

