server:
  port: 9039
  
spring:
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration 
  datasource:
    url: jdbc:postgresql://moddsquad.c7gmm1yiiydz.us-east-1.rds.amazonaws.com/Project2
    username: moddsquad
    password: p4ssw0rd
    driver-class-name: org.postgresql.Driver
  jpa: 
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate: 
      ddl-auto: create


spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username: thevaultbankteam@gmail.com
spring.mail.password: cvyppeqgxhekrroi
spring.mail.properties.mail.smtp.auth: true #needs to be here for email to work, ignore the warning
spring.mail.properties.mail.smtp.starttls.enable: true #needs to be here for email to work, ignore the warning



